# Trivy configuration for VIB scanner
# Ref: https://aquasecurity.github.io/trivy/latest/docs/references/configuration/config-file/

quiet: true
timeout: 5m

vulnerability:
  type:
    - os
    - library
  ignore-unfixed: false

scan:
  security-checks:
    - vuln

db:
  skip-update: false

cache:
  dir: /root/.cache/trivy
